// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

import type { Ai, D1Database } from "@cloudflare/workers-types";

interface CloudflareBindings {
	DB: D1Database;
	AI: Ai;
}
